name: Radar Trading Bot

on:
  schedule:
    - cron: '5 * * * *' # Avvia ogni 10 minuti
  workflow_dispatch: # Questo ci permette di avviarlo anche a mano con un click!

jobs:
  esegui-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Prendi il codice
        uses: actions/checkout@v4

      - name: Prepara Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installa pacchetti
        run: pip install yfinance pandas numpy requests beautifulsoup4

      - name: Esegui il Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} 
          FLASHALPHA_API_KEY: ${{ secrets.FLASHALPHA_API_KEY }}
        run: python bot.py

        
   # --- NUOVO BLOCCO PER LA CACHE ---
      - name: Salva Cache GEX nel Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update GEX cache [skip ci]"
          file_pattern: 'gex_cache.json'
